import { PageHeader } from "@/components/page-header"
import { SiteContainer } from "@/components/site-container"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card"
import { membershipCategories } from "@/lib/data/site"

export default function MembershipPage() {
  return <><PageHeader title="Tagság" description="A MAVET nyitott mindazok számára, akik szakmai munkájukkal vagy elkötelezettségükkel hozzájárulnának a vidékegészségügy fejlődéséhez." /><SiteContainer className="flex flex-col gap-12 py-12 sm:py-16"><section className="flex max-w-3xl flex-col gap-4"><h2 className="text-2xl font-semibold">Miért érdemes kapcsolódni?</h2><p className="leading-7 text-muted-foreground">A MAVET interdiszciplináris szakmai közösség, nyitott és barátságos légkörrel. Rendezvények, szakmai tartalmak és közös munka révén ad lehetőséget a vidékegészségügy jövőjének alakítására.</p></section><section aria-labelledby="kategoriak" className="flex flex-col gap-6"><div className="flex max-w-3xl flex-col gap-2"><h2 id="kategoriak" className="text-2xl font-semibold">Tagsági kategóriák</h2><p className="text-muted-foreground">Válassza ki az élethelyzetéhez és szakmai pályájához illeszkedő kategóriát.</p></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{membershipCategories.map((category) => <Card key={category.id} className="h-full"><CardHeader><CardTitle className="text-lg">{category.name}</CardTitle><CardDescription>{category.description}</CardDescription></CardHeader><CardContent className="flex flex-1 flex-col gap-4"><ul className="flex list-disc flex-col gap-1 pl-5 text-sm leading-6 text-muted-foreground">{category.highlights.map((highlight) => <li key={highlight}>{highlight}</li>)}</ul>{category.fee && <p className="text-sm font-medium text-foreground">{category.fee}</p>}</CardContent><CardFooter>{category.canApply ? <Button className="w-full" render={<a href={`/tagsag/jelentkezes?category=${category.id}`} />} nativeButton={false}>Jelentkezem</Button> : <p className="text-sm leading-6 text-muted-foreground">A Tiszteletbeli tagságról az Elnökség dönt.</p>}</CardFooter></Card>)}</div></section></SiteContainer></>
}
